### ISSUE TITLE
Use design tokens for the 2FA specific (admin) styling

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/django-two-factor-auth#8]
The package (from upstream) includes a 2fa.css file which is used to style the wizard - amongst others it includes a background color for the `.btn` class.

This does not work well together with our custom admin styling overrides, causing mismatched colors that are not easily override-able.

The best solution would be if 2FA uses design tokens for this, which can be included easily by downstream projects.

Example:

Project CSS:

```css
:root {
  --2fa-btn-background: red;
  --2fa-btn-color: white;
}
```

`2fa.css`:

```css
.btn {
    background: var(--2fa-btn-background, #79aec8);
    color: var(--2fa-btn-color, #fff);
    /* other rules... */
}
```
